include ../common.mk

## design_simple: make simple plate designer page from template
design_simple:
	python render.py --template templates/design_simple.html > design_simple.html

## design_dosages: make plate designer page with dosages from template
design_dosages:
	python render.py --template templates/design_dosages.html > design_dosages.html
