include ../common.mk

## serve: run server
serve:
	${RUN_LAB} server.py run

## serve_paths: run server to show various relative paths
serve_paths:
	${RUN_LAB} server_paths.py run

## serve_static: run server to show /static configuration
serve_static:
	${RUN_LAB} server_static_paths.py run
