include ../common.mk

## hello: run "hello" server
hello:
	${RUN_LAB} server_hello.py run

## func: run server that builds app in function
func:
	${RUN_LAB} server_func.py run

## routes: run server that has multiple routes
routes:
	${RUN_LAB} server_routes.py run

## err: run server that handles errors
err:
	${RUN_LAB} server_err.py run
