include ../common.mk

## serve_sql: run server using embedded SQL
serve_sql:
	DB=data/lab.db fastapi dev server_sql.py

## serve_pika: run server using PikaPy
serve_pika:
	DB=data/lab.db fastapi dev server_pika.py
